### ISSUE TITLE
Version reset to catalogs 0.0.0-development

### ISSUE THREAD

**Issue by rondlite** [reactioncommerce/api-service-catalogs#29]
## Issue Description
Version not updated to `1.0.7`, `package.json` says `catalogs 0.0.0-development`

## Possible Solution
Update `package.json` to reflect current version.

### Versions
1.0.7

**Comment by rondlite** [comment]
Bit odd since package has tag Semantic Release..

**Comment by Akarshit** [comment]
The file is updated on the published version on npm's repo. It's just not updated in github.
Here is the reference: https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository
